services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./data/chunks:/data/chunks
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_COUNT=10

    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    command: python backend/app/worker.py
    volumes:
      - .:/app
      - ./data/chunks:/data/chunks
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_COUNT=10
    depends_on:
      - redis

  producer:
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    command: python backend/app/producer.py
    volumes:
      - .:/app
      - ./data/chunks:/data/chunks
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_COUNT=10
    depends_on:
      - redis
