{
  "1-10": [
    "Founders juggle multiple roles across sales, product, and HR",
    "Limited budgets restrict adoption of new tools and services",
    "Early hires carry disproportionate responsibility",
    "Cash flow constraints dominate decision making",
    "Customer acquisition is inconsistent and unpredictable",
    "Hiring even one wrong person has an outsized impact",
    "Processes are mostly ad hoc and undocumented",
    "Founders struggle to balance fundraising with daily operations",
    "Team members often work outside their core expertise",
    "Burnout risk is high due to long hours and overlapping roles",
    "Difficulty in negotiating favorable terms with vendors",
    "Credibility challenges when competing with larger players",
    "Product-market fit validation consumes significant bandwidth",
    "Customer churn hurts more because of small client base",
    "Scaling beyond founder-led sales feels overwhelming",
    "Legal and compliance tasks fall on non-specialists",
    "Talent retention is fragile with limited resources",
    "Prioritizing features vs. revenue opportunities creates tension",
    "One client loss can materially impact revenue",
    "Uncertainty in predicting growth trajectory"
  ],
    "11-50": [
    "Introducing processes without killing agility is challenging",
    "Managers are stretched thin between individual contributor and leadership work",
    "Hiring specialized talent stretches limited budgets",
    "Teams begin to feel growing pains as communication becomes less direct",
    "Founders struggle to delegate without losing visibility",
    "Onboarding new employees takes longer as informal systems break down",
    "Inconsistent processes create inefficiencies across departments",
    "Technology choices made early start showing scalability limits",
    "Balancing company culture with rapid hiring is difficult",
    "Revenue dependency on a few clients creates instability",
    "Middle management roles are unclear and often overlap",
    "Resource allocation conflicts arise between teams",
    "Benefits and compensation packages lag behind larger competitors",
    "Employee turnover hurts disproportionately at this stage",
    "Knowledge silos begin to form as teams grow",
    "Leadership struggles to maintain direct customer relationships",
    "Budget constraints limit investment in growth initiatives",
    "Performance measurement systems are immature",
    "Hiring pace creates strain on HR and recruiting capacity",
    "Early managers lack formal leadership training"
  ],
    "51-200": [
    "Silos emerge as departments formalize and grow",
    "Internal communication slows as headcount increases",
    "Coordination between product, sales, and marketing becomes complex",
    "Hiring managers face pressure to scale teams quickly",
    "Founders lose visibility into day-to-day operations",
    "Company culture starts to fragment across teams",
    "Processes multiply, creating bureaucracy and inefficiency",
    "Decision making slows as more stakeholders get involved",
    "Middle management layers emerge but lack experience",
    "Employee engagement is harder to maintain at scale",
    "Technology stacks need consolidation and upgrades",
    "Budgeting requires more rigorous financial planning",
    "Cross-functional projects struggle with alignment",
    "Onboarding new hires strains HR capacity",
    "Performance management systems remain underdeveloped",
    "Customer support demand grows faster than capacity",
    "Global expansion conversations start but resources are limited",
    "Compliance requirements increase with scale",
    "Competition for talent intensifies in key roles",
    "Scaling sales beyond founder relationships is difficult"
  ],
    "1000-5000": [
    "Bureaucracy slows innovation significantly",
    "Decision making requires extensive stakeholder alignment",
    "Global operations create complex compliance burdens",
    "Internal communication becomes highly fragmented",
    "Mergers and acquisitions introduce constant integration challenges",
    "Employee disengagement rises as leadership feels distant",
    "Layers of middle management create inefficiencies",
    "IT systems require continuous modernization to handle scale",
    "Maintaining data security across geographies is difficult",
    "Departments prioritize local goals over company-wide strategy",
    "Customer experience becomes inconsistent across global regions",
    "Forecasting accuracy decreases with organizational complexity",
    "Internal politics delay execution on strategic initiatives",
    "Standardization efforts clash with local flexibility needs",
    "Maintaining company culture across global offices is a struggle",
    "Compliance with multiple jurisdictions consumes resources",
    "Cross-functional collaboration requires heavy process",
    "Vendor management complexity increases with volume",
    "Employee turnover at scale disrupts key initiatives",
    "Innovation pipelines slow as risk aversion grows"
  ],
    "5000-10000": [
    "Organizational silos harden and slow cross-functional initiatives",
    "Global compliance consumes massive resources across markets",
    "Decision making requires consensus from multiple senior executives",
    "Innovation struggles under risk-averse corporate culture",
    "Employee engagement programs feel generic and ineffective",
    "Internal tools lag behind modern best practices due to legacy systems",
    "IT modernization projects take years to implement",
    "Customer experience varies widely by geography and division",
    "Data governance becomes a top-level board issue",
    "M&A integrations disrupt productivity for extended periods",
    "Layers of approval cycles delay even routine initiatives",
    "Maintaining unified brand identity across regions is challenging",
    "Budgeting cycles are long and rigid, limiting agility",
    "Internal politics dominate resource allocation decisions",
    "Talent retention suffers from limited career mobility",
    "Cultural differences across offices reduce cohesion",
    "Security and privacy compliance multiply with global reach",
    "Coordination across product lines creates conflicts of interest",
    "Strategic priorities shift frequently, creating execution fatigue",
    "Employee turnover costs scale exponentially at this size"
  ],
    "10000-50000": [
    "Bureaucratic layers make innovation nearly impossible",
    "Decision making is painfully slow and highly politicized",
    "Global regulatory compliance becomes a full-time enterprise",
    "M&A activity continuously disrupts organizational stability",
    "Maintaining a unified corporate culture across continents is difficult",
    "Legacy IT infrastructure blocks digital transformation efforts",
    "Employee engagement scores drop as workers feel like numbers",
    "Customer experiences vary widely across divisions and regions",
    "Board-level governance slows down strategic pivots",
    "Budget processes are rigid and inflexible year to year",
    "Cross-border tax and compliance obligations create risk",
    "Coordination across hundreds of teams drains leadership bandwidth",
    "Procurement and vendor management complexity skyrockets",
    "Security vulnerabilities increase with vast global attack surface",
    "Retention of top talent is harder against leaner competitors",
    "Inconsistent adoption of internal tools reduces productivity",
    "Performance measurement systems fail to capture real output",
    "Decision rights are unclear between global and regional leadership",
    "Cost optimization becomes a constant strategic imperative",
    "Execution fatigue spreads due to constant reorganizations"
  ],
    "50000-100000": [
    "Bureaucracy creates gridlock for even minor decisions",
    "Innovation pipelines stall under excessive process layers",
    "Compliance and regulatory overhead consume massive budgets",
    "Employee disengagement becomes systemic and hard to reverse",
    "Cross-border governance introduces constant legal challenges",
    "M&A integrations take years and rarely deliver expected synergies",
    "Technology transformation projects often fail at this scale",
    "Customer experience lacks consistency across business units",
    "Board oversight slows experimentation and risk-taking",
    "Procurement inefficiencies waste millions annually",
    "Vendor ecosystems become nearly impossible to manage",
    "Internal communication collapses into silos and echo chambers",
    "Leadership struggles to maintain cultural cohesion worldwide",
    "Retaining high performers requires extreme compensation packages",
    "Internal politics dominate decision-making processes",
    "Security threats multiply with sprawling global infrastructure",
    "Constant reorganizations undermine long-term execution",
    "Financial reporting cycles delay fast responses to market shifts",
    "Alignment between global strategy and local execution is weak",
    "Employees feel disconnected from mission and leadership vision"
  ],
    "100000+": [
    "Decision making at scale becomes paralyzed by politics and hierarchy",
    "Innovation slows dramatically under massive organizational inertia",
    "Compliance costs run into billions across multiple jurisdictions",
    "Cultural cohesion is nearly impossible across hundreds of offices",
    "Employees feel disconnected and anonymous in a giant workforce",
    "Internal communication is dominated by bureaucracy and red tape",
    "Technology modernization requires decades-long initiatives",
    "Customer experience is inconsistent across divisions and geographies",
    "M&A activity causes constant restructuring and instability",
    "Board and shareholder pressures override long-term strategy",
    "Procurement processes waste enormous amounts of capital",
    "Vendor ecosystems sprawl into unmanageable complexity",
    "Internal politics create fiefdoms that block collaboration",
    "Security breaches at this scale cause systemic global risk",
    "Leadership succession becomes a critical governance challenge",
    "Employee turnover costs billions annually at this size",
    "Aligning global strategy with local execution is nearly impossible",
    "Cost optimization efforts trigger waves of layoffs and morale loss",
    "Decision rights between corporate HQ and regional offices remain unclear",
    "Execution fatigue dominates due to constant restructuring cycles"
  ]
}

